name: "AWS Deploy workflow"

on:
  pull_request:
    types: [closed]

permissions:
  id-token: write

jobs:
  aws:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: aws cli configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::650267257878:role/OIDC"
          aws-region: "us-east-1"

      - name: try cli
        run: |
          echo -e "this is deploy job\n"
          sam 
          # aws s3 ls
