name: "Test workflow"
on:
  pull_request:
    branches: [dev]

permissions:
  id-token: write

jobs:
  test:
    if: false
    runs-on: ubuntu-latest

    steps:
      - name: pass test
        run: |
          echo "test passed" && exit 0

  jest:
    runs-on: ubuntu-latest
    if: true

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3

      - name: install deps & build
        run: |
          yarn install --include=dev
          yarn build

      - name: run test
        run: |
          cat non-existent-file
          # yarn test:exit
